#- include_vars: "{{ansible_os_family}}.yml"
- name: remove index file
  file:
    path: "{{ path }}/index.html"
    state: absent
- name: create index file
  copy:
    content: |
            <?php echo 'hello world' ?>
    dest: "{{ path }}/{{index}}"

