#- include_vars: "{{ansible_os_family}}.yml"
- name: populate service facts
  service_facts:
- name: stop "{{ package_service }}"
  service:
    name: "{{ package_service }}"
    state: stopped
  when: "package_service in services"
  notify:
  - start "{{ package_service }}"

